In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Defining vocabulary size
vocab_size=10000

In [5]:
## One Hot Representation
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
one_hot_repr

[[4100, 1283, 319, 2449],
 [4100, 1283, 319, 6172],
 [4100, 6918, 319, 6450],
 [5800, 6825, 82, 7897, 8111],
 [5800, 6825, 82, 7897, 5876],
 [5774, 4100, 7675, 319, 9579],
 [9064, 8431, 5164, 7897]]

In [11]:
## Word Embedding Representation
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences

In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 4100, 1283,  319, 2449],
       [   0,    0,    0,    0, 4100, 1283,  319, 6172],
       [   0,    0,    0,    0, 4100, 6918,  319, 6450],
       [   0,    0,    0, 5800, 6825,   82, 7897, 8111],
       [   0,    0,    0, 5800, 6825,   82, 7897, 5876],
       [   0,    0,    0, 5774, 4100, 7675,  319, 9579],
       [   0,    0,    0,    0, 9064, 8431, 5164, 7897]])

In [13]:
## Feature Representation
dim = 10

In [14]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

c:\ML\aivenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 452ms/step


array([[[-0.02783592, -0.03274955,  0.01851949,  0.00494291,
          0.03932139, -0.03857181,  0.01516644,  0.00766661,
         -0.00716487,  0.03328792],
        [-0.02783592, -0.03274955,  0.01851949,  0.00494291,
          0.03932139, -0.03857181,  0.01516644,  0.00766661,
         -0.00716487,  0.03328792],
        [-0.02783592, -0.03274955,  0.01851949,  0.00494291,
          0.03932139, -0.03857181,  0.01516644,  0.00766661,
         -0.00716487,  0.03328792],
        [-0.02783592, -0.03274955,  0.01851949,  0.00494291,
          0.03932139, -0.03857181,  0.01516644,  0.00766661,
         -0.00716487,  0.03328792],
        [-0.02126796,  0.00262239,  0.01655883,  0.03311351,
          0.03257629, -0.00692447,  0.0182048 , -0.01677576,
         -0.03114974,  0.03424938],
        [ 0.03072511, -0.01259281,  0.01286867,  0.02752448,
          0.00779567,  0.01300902, -0.00517061,  0.02904757,
         -0.0156162 ,  0.01030884],
        [ 0.00985729,  0.03248474,  0.02138472, -0.0

In [32]:
embedded_docs[0]

array([   0,    0,    0,    0, 4100, 1283,  319, 2449])

In [39]:
model.predict(embedded_docs[0].reshape(1, 8))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[[-0.02783592, -0.03274955,  0.01851949,  0.00494291,
          0.03932139, -0.03857181,  0.01516644,  0.00766661,
         -0.00716487,  0.03328792],
        [-0.02783592, -0.03274955,  0.01851949,  0.00494291,
          0.03932139, -0.03857181,  0.01516644,  0.00766661,
         -0.00716487,  0.03328792],
        [-0.02783592, -0.03274955,  0.01851949,  0.00494291,
          0.03932139, -0.03857181,  0.01516644,  0.00766661,
         -0.00716487,  0.03328792],
        [-0.02783592, -0.03274955,  0.01851949,  0.00494291,
          0.03932139, -0.03857181,  0.01516644,  0.00766661,
         -0.00716487,  0.03328792],
        [-0.02126796,  0.00262239,  0.01655883,  0.03311351,
          0.03257629, -0.00692447,  0.0182048 , -0.01677576,
         -0.03114974,  0.03424938],
        [ 0.03072511, -0.01259281,  0.01286867,  0.02752448,
          0.00779567,  0.01300902, -0.00517061,  0.02904757,
         -0.0156162 ,  0.01030884],
        [ 0.00985729,  0.03248474,  0.02138472, -0.0